INSERT INTO categories (name, slug, description, hero_tone) VALUES
    ('Lifestyle', 'lifestyle', 'Everyday silhouettes with premium comfort and clean form.', '#f3c96a'),
    ('Running', 'running', 'Responsive trainers for tempo runs and fast daily mileage.', '#ff7b61'),
    ('Court', 'court', 'Retro basketball references refined for modern streetwear.', '#9fd5ff'),
    ('Trail', 'trail', 'Grip-heavy off-road pairs built for mixed weather sessions.', '#9ed17b');

INSERT INTO shoes (
    sku,
    name,
    slug,
    brand,
    silhouette,
    short_description,
    description,
    price,
    primary_image,
    secondary_image,
    available_sizes,
    accent_colors,
    highlights,
    featured,
    new_arrival,
    best_seller,
    category_id
) VALUES
    (
        'NB-9060-BEIGE',
        'New Balance 9060 Drift Sand',
        'new-balance-9060-drift-sand',
        'New Balance',
        'Chunky lifestyle',
        'A plush daily pair with sculpted midsoles and warm neutral layering.',
        'The 9060 Drift Sand blends archival New Balance codes with a sculpted, future-facing sole. It is positioned as the hero lifestyle option for customers who want premium softness, easy styling and a strong statement shape.',
        4390000,
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=80',
        '39|40|41|42|43|44',
        '#ead7bb|#c7a16b|#2f2a24',
        'ABZORB comfort platform|Layered suede and mesh upper|Statement outsole geometry',
        TRUE,
        TRUE,
        TRUE,
        1
    ),
    (
        'ASICS-GEL-KAYANO',
        'ASICS Gel Kayano Skyline',
        'asics-gel-kayano-skyline',
        'ASICS',
        'Stability running',
        'A stable trainer for high-mileage runners who still want visual energy.',
        'Gel Kayano Skyline is positioned as the dependable running choice in the new stack. The midsole tuning and supported geometry make it suitable for long easy miles, while the upper keeps the look sharp enough for everyday wear.',
        3890000,
        'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=1200&q=80',
        '40|41|42|43|44|45',
        '#1b3f68|#85d0ff|#f5f7fa',
        'Stability-led ride|Engineered mesh ventilation|Long-run cushioning',
        TRUE,
        FALSE,
        TRUE,
        2
    ),
    (
        'NIKE-VOMERO-18',
        'Nike Vomero 18 Ember',
        'nike-vomero-18-ember',
        'Nike',
        'Max cushion running',
        'Soft high-stack foam with a bright race-day energy palette.',
        'Vomero 18 Ember sits at the intersection of recovery comfort and bold finish. It is the pair for customers who want a high-stack everyday runner that still reads fresh and premium on shelf and in campaign visuals.',
        4190000,
        'https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1463100099107-aa0980c362e6?auto=format&fit=crop&w=1200&q=80',
        '40|41|42|43|44',
        '#ff784f|#271c1a|#f8e7dc',
        'High-stack foam ride|Smooth rocker transition|Bold limited color palette',
        FALSE,
        TRUE,
        FALSE,
        2
    ),
    (
        'ADIDAS-SAMBA-OG',
        'Adidas Samba OG Pearl',
        'adidas-samba-og-pearl',
        'Adidas',
        'Court classic',
        'Low-profile icon updated with soft leather and pearl gum contrast.',
        'Samba OG Pearl keeps the familiar terrace DNA but pushes the material story toward a cleaner, fashion-forward execution. It gives the new frontend a recognizable anchor product with wide consumer appeal.',
        2890000,
        'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80',
        '36|37|38|39|40|41|42',
        '#f4efe6|#cfb17c|#191919',
        'Soft leather finish|Classic gum tooling|Slim styling profile',
        FALSE,
        FALSE,
        TRUE,
        3
    ),
    (
        'SALOMON-XA-PRO',
        'Salomon XA Pro Ridge',
        'salomon-xa-pro-ridge',
        'Salomon',
        'Trail utility',
        'Technical traction and quick-lace utility for mixed-city terrain.',
        'XA Pro Ridge gives the catalog a technical trail pillar. The pair is built around grip, weather-ready layering and a visual language that feels modern enough for gorpcore-led styling and real outdoor use.',
        4690000,
        'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1200&q=80',
        '40|41|42|43|44|45',
        '#394b3d|#9ed17b|#dce7da',
        'All-terrain grip|Quick-lace lockdown|Protective upper overlays',
        TRUE,
        TRUE,
        FALSE,
        4
    ),
    (
        'ON-CLOUDMONSTER',
        'On Cloudmonster Mist',
        'on-cloudmonster-mist',
        'On',
        'Performance lifestyle',
        'Swiss-engineered bounce with a minimal shell and fluid neutral palette.',
        'Cloudmonster Mist is the bridge between performance and elevated daily wear. The exaggerated pod geometry helps the storefront communicate technology without losing the fashion-first visual rhythm of the rebrand.',
        4990000,
        'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=1200&q=80',
        '39|40|41|42|43|44',
        '#f2f4f7|#9aa7b2|#1f2937',
        'CloudTec cushioning|Everyday performance profile|Minimal premium finish',
        FALSE,
        TRUE,
        TRUE,
        1
    );
